{% set name = "conda-devenv" %}
{% set version = "0.9.2" %}
{% set hash = "493017fc98fadd3a6b4f0a286423fc4c8b2c7ae69b2d3dd454b7d078917b6606" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/ESSS/conda-devenv/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - conda-devenv = conda_devenv.devenv:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - pyyaml

test:
  imports:
    - conda_devenv
  commands:
    - conda-devenv --help

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A tool to work with multiple projects in develop-mode using conda-env.'
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
