travis:
  secure:
    BINSTAR_TOKEN: HmynJaNpkTGv3nxKy0Y3WB383xyQoHteSV2IR4bH8OH42nbjMwE8fsmHDUkb1wNHyO9lEjvIgTtv1OGFdrAGmu080OBz6gMS5C6PdbmtcGAc4nBucCzrzPWA1dTYja5FXpQYvcRmsbWo/AJ+kFv3UjajBYsmuN2S9u3Zg+wVkRfkYqnV7re5RSdPjVb4Bl1vgEU3lcyLCjVY5EYoGoM08pCphYzU/19VqebhU3pC7vQU3RV85dWepLbKs3BjJ983CautfGSY/QzWlHcvFF4RzHxLg2SJMUCL20lMIgs0ZZ8IhJGYh0OKP56AdZDmqG3oiv4fjn4gV05qdYgCel6VDG4o53RSC5ZnIkPNhoAhqtJ70ZwgMxhAl6/w5RVaT7n2vO9xExBUMfy3J+bx1Kc6y+LjTTrjMz9VwIgBicdTd1TqxLoEhP2VfsLi7fNHapgtkiLXOgCeEciFG9vIFwx9K7N6S3iErQcDMug4owo59XBSBV/jdU9O6yCLX/jdwWtm2Ydc6+w/yIrNnFIUt98wZA9A2p8ETa5if9ujIOorMXO39325rdHnOk9RhumG/r1fHmAVriMaZHHarbD5KknYen7sg4JQNmkOTi9+ol6R3WC6yY+SftBtoe5Vd4Dr3iCimlCMwXIkrlxg+cQRDNRRP8iyDPlhQa/S7nY5kyxicQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
