travis:
  secure:
    BINSTAR_TOKEN: aTKW90XC49l1uP3d3BiMrBPCQzHPlr1nnpQNUfg2AMNSNVeQL8cHBcs8pUlUHEnYaq9Ae3HxHZM25Mt4crKU/8e4u50r0GNr54Q1zQ7n8YpbI7gIUubf3hQAFmnnbMTMC4GbFOZP+vD8UMuOp32a5yfstl+bapFlp4MDKOZ/DzG7RGm0DzEM13H2Kkzj0KqzvA5Rq/X5MEOgcstBMbd+V3k1+DHQJMgH0HKonAUQAkw3+S37fL1Qh3zDaT4ubAFQ8AU3ZZRVEHUbA2SB4/jzFCVIXi1yaIw5uOL95KWYsMsUNWrvtJeAvqUglmFJkaUhW/8K9kpFyUXcxKcjcH1GsKuEShm33o41R4wdPlIxbmc3dFAs3gg/32u/BNaAo58Q2cIW6pH3px27ogpI7fxJCbrJcOLVOWcsywVWZCFZj+9sQHeLhnkcG9Jl+cIy1LcejNb+2Kh7kEqwC522RobKEfrvOrPDYTp8ZTwDHMpnnT7kDvuRItgAUzaA3iZ3cMn9IvRqysmwHPkl7ATglHrTcS1mbvmbtdov5coq/AhEtr1P0QxOZayYbidRyr+KQn58Szb913WgTLo4CEJ1zqSO0Dauh/gfrS3//sY+shQQmuQLD4Y3557/vwYIio1NDjS9A7bF2lseM6OUPKZsY0bCUDw/A6asMhorbLrH6EWr1Dw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
