travis:
  secure:
    BINSTAR_TOKEN: Y0KUL4zfeetleIG/c8lq5z18YYW3IzEIS8glRkd9JkJTdsxXnggoiG6SdPkOfmVaR+3rQWz590gny01OzZmN4WHlSs+RTFRIFVCqyvOD/T3zPcFM0ilJLuElRP6TTd3FlhZBNhGXN0n3cf/JIYA9IAUQBLT3r3DF2JFX+RS946noFVfm4/SB7xKfzBpTlyHTfPKF0X4jN9l0jz2WJgk3obsrBFmyB1/bIR1xrp/v+DhRtRfSwCOiLwjQkrwoDhq0Ai4kJqHd6r6p3W6tGukqnQUPiTpIEdGAaPMuRT9EwDAqSQWCyXK79UBaYjfGjz2iJx47oVsCEIB7Ae2PgZ7Ca9YvVFCZ2d1Z52ovhS0aY/TK4ZfDcKlyDN5AEbOgDIm9eTMooiA40KjG0/xQsGLbyYdpCT2PqtgVl6qVenWolUOJVuufJSrmUIJ093ZEHnZwaeokjcoWTu59DbngQwQEbGTkGBVSwcPOGheqwveJz7iS4ESmb775waI6kcbqTkaMlhw+zQhKDKgx01hdhyRwN0ZDNjoRGl33crzdMPyA2sYsBodOKlLlAv59LqmexwiZygKW6sqARNjFUKKMK+gCWpyJBlUMpEjJauz9pu1rFpk2KEEyqU+Sg93fm6dU3LQFO2zGIqalU9ReUmhQznuRvYRyaZ5M2SXRx5P1M2Xzufk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
