travis:
  secure:
    BINSTAR_TOKEN: 0ftQncKIdhe9He7M3LXH0MSNwU+GuMuFZk/5dHtBVm+nuxCi1FaOwIQc+l+EcPREYy+b8ahjZZatA7RFuMlKGAySerYyLo6SmEPSXZy8OBY8ax+czLjCPmHpiK1gnEEgtxWcpe9ynsyzc4qHdKft0DWHrVP+ReFriAZlPyM6WpH5oGnEs8rjID+Eb2r7Y83iNtM6nphbeU1mTzjGusSMA7WB4ZJN8W1PvleLPiv/c2wN4TMGhvnsa/JBV6Ogmq3smMmqm643D/ARn6DgBGu8ICd54Sqyyyck1dcMIBbExJZ8tkglnmhhI9ybw5QDGlgczP/b9xmWrOtKZNZPLu5rnA+1sdbA+wtI5acR1SSnq9OkelFJyDrYH4CkqTI/05mJIACMCJQnz+hzaH8Y2u6hc1AzYFwRwycV7bmPUxS7I4Hq4Pc8clvX5f45orekv0SfME1w9hqxVQIgwCTgEa9+gWu40Y0N9ZtlNreyaPiKOOH6xxJU3OvScqhmOEqo2q2+yN8VDNFGH7AStuzQ1EI/1NxcwauIGseXZ1odRtTmeJV7+AhFQNueS+vXyzUDAUeNG+WCCubfxzVGegQlpvJ/9J1YW+l3uDnBoxtDTIEs7npxip7KQ/ThbqmY16IHCu637wubIi+M3d/jo7u+4mlly7vj3mo1JIsQqydw6yCsigQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
